# Generated by Django 2.2 on 2021-02-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=100, verbose_name='Магазин')),
                ('title', models.CharField(max_length=455, verbose_name='Название книги')),
                ('author', models.CharField(blank=True, max_length=455, null=True, verbose_name='Автор')),
                ('link', models.CharField(max_length=355, unique=True, verbose_name='Ссылка на товар')),
                ('img_link', models.CharField(max_length=355, verbose_name='Ссылка на картинку')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['price'],
            },
        ),
    ]
