# Generated by Django 2.2 on 2020-10-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='books',
            name='shop',
            field=models.CharField(default='No', max_length=150, verbose_name='Магазин'),
            preserve_default=False,
        ),
    ]
