# Generated by Django 2.2 on 2020-10-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201030_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img_link',
            field=models.CharField(max_length=250, verbose_name='Ссылка на книгу'),
        ),
        migrations.AlterField(
            model_name='books',
            name='link',
            field=models.CharField(max_length=250, unique=True, verbose_name='Ссылка на товар'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название книги'),
        ),
    ]
