# Generated by Django 2.2 on 2020-10-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201030_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img_link',
            field=models.CharField(max_length=250, verbose_name='Ссылка на картинку'),
        ),
    ]
