# Generated by Django 2.2 on 2020-10-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201030_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
