# Generated by Django 2.2 on 2020-11-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201030_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=150, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(blank=True, verbose_name='Цена'),
        ),
    ]
