# Generated by Django 2.2 on 2020-11-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201103_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='link',
            field=models.CharField(max_length=250, verbose_name='Ссылка на товар'),
        ),
    ]
