# Generated by Django 2.2 on 2020-11-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201104_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='books',
            name='img_link',
            field=models.CharField(max_length=255, verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='books',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Ссылка на товар'),
        ),
        migrations.AlterField(
            model_name='books',
            name='shop',
            field=models.CharField(max_length=100, verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название книги'),
        ),
    ]
