# Generated by Django 2.2 on 2020-11-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201104_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='link',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ссылка на товар'),
        ),
    ]
