# Generated by Django 2.2 on 2020-11-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201104_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['price'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=455, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='books',
            name='img_link',
            field=models.CharField(max_length=355, verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='books',
            name='link',
            field=models.CharField(max_length=355, unique=True, verbose_name='Ссылка на товар'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=455, verbose_name='Название книги'),
        ),
    ]
